url: https://doergn.github.io
baseurl: /

# Site settings
title: Dirk Lehmann
email: your-email@domain.com
description: "Dirk Lehmann, Speaker, DevOps Enthusiast"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/doergn
  - title: linkedin
    url: https://www.linkedin.com/in/dirk-lehmann-7712bb125/
  - title: github
    url: http://github.com/doergn

# Build settings
markdown: kramdown
permalink: pretty
